version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
        image: mindscribe:latest
        container_name: mindscribe
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        restart: unless-stopped
